export type SyncPlayContext = {
  inGroup: boolean;
  groupId: string;
  groupName: string;
  sessionId: string;
  deviceId: string;
  participantCount: number;
  unavailable: boolean;
  membershipSource: string;
  accessResolved: boolean;
  passwordProtected: boolean;
  authorized: boolean;
  isOwner: boolean;
};

export type RoomAccessInfo = {
  inGroup: boolean;
  groupId: string;
  groupName: string;
  sessionId: string;
  deviceId: string;
  participants: string[];
  exactMembership: boolean;
  membershipSource: string;
  passwordProtected: boolean;
  authorized: boolean;
  isOwner: boolean;
};

export type RoomEvent = {
  id: string;
  sequence: number;
  groupId: string;
  type: string;
  userId: string;
  userName: string;
  sessionId: string;
  createdAtUtc: string;
  text: string;
  replyTo: ReplyTarget | null;
  emoji: string;
  playbackAction: string;
  fromPositionTicks: unknown;
  toPositionTicks: unknown;
  positionSeconds: number | null;
  itemId: string;
  itemName: string;
  clientEventId: string;
  eventKey: string;
  isTyping: boolean | null;
  optimistic?: boolean;
};

export type ReplyTarget = {
  eventId: string;
  userId: string;
  userName: string;
  messagePreview: string;
  createdAt: string;
};

export type ChatMessage = {
  id: string;
  sequence: number;
  groupId: string;
  userId: string;
  userName: string;
  text: string;
  replyTo: ReplyTarget | null;
  createdAtUtc: string;
  eventKey: string;
  optimistic?: boolean;
};

export type MessageGroupModel = {
  key: string;
  senderKey: string;
  userName: string;
  createdAtUtc: string;
  messages: ChatMessage[];
};

export type PlaybackEventType = "playback.start" | "playback.play" | "playback.pause" | "playback.seek";

export type PlaybackTimelineItem = {
  kind: "playback";
  key: string;
  id: string;
  sequence: number;
  type: PlaybackEventType;
  userName: string;
  createdAtUtc: string;
  fromPositionTicks: number | null;
  toPositionTicks: number | null;
  itemId: string;
  itemName: string;
  eventKey: string;
};

export type TimelineItem =
  | { kind: "messageGroup"; key: string; group: MessageGroupModel }
  | PlaybackTimelineItem;

export type DrawerSide = "right" | "left";
export type TriggerMode = "native-header" | "native-video-osd" | "desktop-overlay-fallback" | "native-missing";

export type TriggerIndicatorState = {
  unreadChatIndicatorActive: boolean;
  playbackActivityIndicatorActive: boolean;
  lastUnreadEventType: string | null;
  lastUnreadEventSeq: number | null;
  lastActivityEventType: string | null;
  lastActivityEventSeq: number | null;
};

export type TypingRemoteUser = {
  key: string;
  userName: string;
  userId: string;
  sessionId: string;
  groupId: string;
  expiresAtMs: number;
};

export type ChatState = {
  drawerOpen: boolean;
  drawerSide: DrawerSide;
  drawerWidth: number;
  drawerWidthSource: string;
  drawerResizeActive: boolean;
  drawerWidthMin: number;
  drawerWidthMax: number;
  drawerBackgroundAlpha: number;
  drawerBackgroundAlphaSource: string;
  customCssDisabled: boolean;
  syncPlay: SyncPlayContext;
  messages: ChatMessage[];
  groups: MessageGroupModel[];
  timelineItems: TimelineItem[];
  sending: boolean;
  triggerIndicator: TriggerIndicatorState;
  typingLocalActive: boolean;
  typingRemoteUsers: TypingRemoteUser[];
  typingTtlMs: number;
  replyTarget: ReplyTarget | null;
  replyTargetFound: boolean;
  messageActionMenu: MessageActionMenuState;
  highlightedMessageId: string | null;
};

export type ChatActions = {
  openDrawer: () => void;
  closeDrawer: () => void;
  toggleDrawer: () => void;
  toggleDrawerSide: () => void;
  setDrawerWidth: (width: number, source: string) => void;
  resetDrawerWidth: () => void;
  setDrawerBackgroundAlpha: (alpha: number) => void;
  resetDrawerBackgroundAlpha: () => void;
  setCustomCssDisabled: (disabled: boolean) => void;
  resetDrawerPreferences: () => void;
  setDrawerResizeActive: (active: boolean) => void;
  noteComposerInput: (value: string) => void;
  stopTyping: (reason: string) => void;
  sendMessage: (text: string) => Promise<boolean>;
  sendReaction: (emoji: string) => Promise<boolean>;
  setInputFocused: (focused: boolean) => void;
  startReply: (message: ChatMessage) => void;
  cancelReply: (reason: string) => void;
  openMessageActionMenu: (message: ChatMessage, x: number, y: number) => void;
  closeMessageActionMenu: (reason: string) => void;
  copyMessage: (message: ChatMessage) => Promise<boolean>;
  highlightMessage: (messageId: string) => void;
  unlockRoom: (password: string) => Promise<RoomActionResult>;
  setRoomPassword: (password: string) => Promise<RoomActionResult>;
  disableRoomPassword: () => Promise<RoomActionResult>;
};

export type RoomActionResult = {
  success: boolean;
  message: string;
};

export type MessageActionMenuState = {
  open: boolean;
  message: ChatMessage | null;
  x: number;
  y: number;
  copiedMessageId: string | null;
  feedback: string;
};

export type ReactionOverlayItem = {
  id: string;
  emoji: string;
  clientEventId: string;
  createdAtMs: number;
  expiresAtMs: number;
  left: number;
  top: number;
  dx: number;
  rise: number;
  durationMs: number;
  scale: number;
  reducedMotion: boolean;
};

export type ReactionEvent = {
  emoji: string;
  clientEventId: string;
  userId: string;
  userName: string;
  groupId: string;
  itemId: string;
  itemName: string;
  positionSeconds: number | null;
  createdAtUtc: string;
};

export type JellyChatDebugDetails = {
  layout: Record<string, unknown>;
  events: Record<string, unknown>;
  playback: Record<string, unknown>;
  reactions: Record<string, unknown>;
  emojiPicker: Record<string, unknown>;
  lifecycle: Record<string, unknown>;
};

export type JellyChatDebug = Record<string, unknown> & {
  loaded: boolean;
  frontend: "react";
  mounted: boolean;
  reactMounted: boolean;
  injectionMode: "self-contained";
  assetMode: "plugin-endpoint";
  assetBasePath: string;
  assetBasePathSource: string;
  assetBasePathError: string | null;
  injectedAssetBaseUrl: string;
  injectedScriptSrc: string;
  fileTransformationRequired: false;
  injectedAssetVersion: string;
  injectionMarkerFound: boolean;
  assetCssLoaded: boolean;
  assetJsLoaded: boolean;
  rootCount: number;
  buttonCount: number;
  intervalCount: number;
  listenerCount: number;
  apiMode: "events";
  lastSequence: number;
  eventCount: number;
  eventPollIntervalMs: number;
  lastImmediateRefreshAt: string | null;
  optimisticEventCount: number;
  pendingOptimisticEventCount: number;
  confirmedOptimisticEventCount: number;
  lastOptimisticClientEventId: string | null;
  lastOptimisticActorName: string | null;
  lastResolvedActorName: string | null;
  lastActorFallbackReason: string | null;
  lastConfirmedClientEventId: string | null;
  lastTimelineMergeStrategy: string | null;
  lastTimelinePreservedCount: number;
  lastTimelineReplacedCount: number;
  lastTimelineAddedCount: number;
  lastTimelineUpdatedCount: number;
  lastTimelineClearedAt: string | null;
  timelineContainerRemountCount: number;
  timelinePinnedToBottom: boolean;
  lastScrollPreservedAt: string | null;
  lastAutoScrollReason: string | null;
  lastEventRoundTripMs: number | null;
  lastEventMergeCount: number;
  replyActive: boolean;
  replyTargetEventId: string | null;
  replyTargetFound: boolean;
  contextMenuOpen: boolean;
  lastCopiedMessageId: string | null;
  highlightedMessageId: string | null;
  groupedMessageCount: number;
  messageActionMenuOpen: boolean;
  lastMessageAction: string | null;
  lastApiMethod: string;
  lastApiPath: string;
  lastApiUrlPath: string;
  lastApiUrlSource: string;
  lastApiUrlError: string | null;
  lastApiStatus: number | null;
  lastApiError: string | null;
  playbackListenerCount: number;
  playbackEventCount: number;
  seekDebounceMs: number;
  lastPlaybackEventType: string | null;
  lastPlaybackEventPostAt: string | null;
  lastPlaybackSuppressedReason: string | null;
  lastPauseDetectedAt: string | null;
  lastPlayDetectedAt: string | null;
  lastSeekStartedAt: string | null;
  lastSeekSettledAt: string | null;
  lastSeekFromSeconds: number | null;
  lastSeekToSeconds: number | null;
  lastSeekDirection: string | null;
  lastSeekSuppressedReason: string | null;
  seekIntentWindowMs: number;
  lastSeekIntentWindowMs: number;
  seekThresholdSeconds: number;
  lastSeekDeltaSeconds: number | null;
  lastSeekIntentAgeMs: number | null;
  lastSeekCandidateFromSeconds: number | null;
  lastSeekCandidateToSeconds: number | null;
  lastSeekCandidateReason: string | null;
  seekInProgress: boolean;
  seekSuppressPlaybackUntil: string | null;
  lastLocalPlaybackInputAt: string | null;
  lastLocalPlaybackInputType: string | null;
  lastLocalPlaybackInputTarget: string | null;
  lastLocalPlayPauseIntentAt: string | null;
  lastLocalSeekIntentAt: string | null;
  currentPlaybackItemId: string | null;
  currentPlaybackItemTitle: string | null;
  playbackStartLoggedForItem: string | null;
  lastPlaybackStartAt: string | null;
  lastPlaybackStartTitle: string | null;
  lastPlaybackStartItemId: string | null;
  startupGuardUntil: string | null;
  lastSeekEventAt: string | null;
  reactionOverlayCount: number;
  reactionOverlayMax: number;
  reactionEventCount: number;
  lastReactionEmoji: string | null;
  lastReactionSentAt: string | null;
  lastReactionReceivedAt: string | null;
  lastReactionClientEventId: string | null;
  lastReactionDroppedReason: string | null;
  emojiPickerOpen: boolean;
  emojiSearchQuery: string;
  favoriteEmojiCount: number;
  recentlyUsedEmojiCount: number;
  quickReactionSlots: string[];
  quickReactionEditMode: boolean;
  selectedQuickReactionSlotIndex: number | null;
  lastQuickReactionEditAction: string | null;
  messageCount: number;
  timelineCount: number;
  currentGroupId: string;
  currentSessionId: string;
  currentDeviceId: string;
  currentDeviceName: string;
  currentClientName: string;
  currentApiDeviceId: string;
  syncPlayMembershipSource: string;
  syncPlayResolutionReason: string;
  syncPlayResolutionState: string;
  syncPlaySessionMatchCount: number;
  syncPlayCurrentUserSessionCount: number;
  syncPlayCurrentUserSessionIds: string[];
  syncPlayMatchedSessionIds: string[];
  syncPlaySameAccountMultiClient: boolean;
  syncPlayAmbiguousSession: boolean;
  syncPlayGroupCount: number;
  syncPlayGroupsUnavailable: boolean;
  syncPlayInGroup: boolean;
  syncPlayActiveGroupId: string;
  syncPlayNotInRoomReason: string | null;
  syncPlayRoomInGroup: boolean;
  syncPlayRoomGroupId: string;
  syncPlayRoomSessionId: string;
  syncPlayRoomDeviceId: string;
  syncPlayRoomExactMembership: boolean;
  syncPlayRoomMembershipSource: string;
  syncPlayRoomRequestError: string | null;
  syncPlayClientSignalSource: string;
  syncPlayClientSignalGroupId: string;
  syncPlayClientSignalKnown: boolean;
  syncPlayClientSignalInGroup: boolean;
  lastSyncPlayResolutionError: string | null;
  drawerOpen: boolean;
  drawerSide: DrawerSide;
  drawerWidth: number;
  drawerWidthSource: string;
  drawerResizeActive: boolean;
  drawerWidthMin: number;
  drawerWidthMax: number;
  drawerBackgroundAlpha: number;
  drawerBackgroundAlphaSource: string;
  triggerMode: TriggerMode;
  triggerHostFound: boolean;
  triggerHostSelector: string;
  lastTriggerMountError: string | null;
  triggerRoute: string;
  triggerActiveRootSelector: string;
  triggerCandidateCount: number;
  triggerVideoHostCandidateCount: number;
  triggerHeaderHostCandidateCount: number;
  triggerObserverUpdateCount: number;
  triggerObserverLastReason: string;
  triggerObserverLastUpdateAt: string | null;
  desktopTriggerFallbackActive: boolean;
  desktopFallbackHostCount: number;
  desktopFallbackDuplicateCount: number;
  desktopFallbackParentSelector: string;
  triggerCount: number;
  unreadChatIndicatorActive: boolean;
  playbackActivityIndicatorActive: boolean;
  lastUnreadEventType: string | null;
  lastUnreadEventSeq: number | null;
  lastActivityEventType: string | null;
  lastActivityEventSeq: number | null;
  typingLocalActive: boolean;
  typingRemoteCount: number;
  typingRemoteUsers: string[];
  lastTypingEventAt: string | null;
  typingTtlMs: number;
  runtimeShell: string;
  clientShell: string;
  isJellyfinDesktop: boolean;
  layoutMode: string;
  desktopVideoSafeMode: boolean;
  desktopOverlayCssFallbackApplied: boolean;
  videoSurfaceInsetApplied: boolean;
  videoSurfaceResizeSuppressed: boolean;
  playerControlsInsetApplied: boolean;
  playerSubtitlesInsetApplied: boolean;
  headerControlsInsetApplied: boolean;
  counts: Record<string, unknown>;
  status: Record<string, unknown>;
  last: Record<string, unknown>;
  details: JellyChatDebugDetails;
  lastEventPollAt: string | null;
  lastEventPostAt: string | null;
  lastError: string | null;
  lastInjectionError: string | null;
  dump: () => Record<string, unknown>;
  reset: () => Record<string, unknown>;
  setVerbose: (enabled: boolean) => Record<string, unknown>;
  getSummary: () => Record<string, unknown>;
};

declare global {
  interface Window {
    ApiClient?: any;
    Dashboard?: any;
    JellyChatDebug?: JellyChatDebug;
    Events?: any;
    ServerNotifications?: any;
    __JELLYCHAT_LOADED__?: boolean;
    __JELLYCHAT_REFRESH_INTERVAL_ID__?: number | null;
    __JELLYCHAT_LISTENERS_BOUND__?: boolean;
    __JELLYCHAT_PLAYBACK_LISTENERS_BOUND__?: boolean;
    __JELLYCHAT_HISTORY_PATCHED__?: boolean;
    __jellyChatLoaded?: boolean;
  }
}
